lingin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import tugas1_stats.urls as stats
import tugas1_friends.urls as friends
import tugas1_profil.urls as profile
import tugas1_status.urls as status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(status,namespace='status')),
    url(r'^stats/', include(stats,namespace='stats')),
    url(r'^friends/', include(friends,namespace='friends')),
    url(r'^profile/', include(profile,namespace='profile')),
]

tugas1_friends/urls.py
from django.conf.urls import url
from .views import index, friend_post, delete_friend

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
    url(r'^$', index, name='index'),
    url(r'^friend_post', friend_post, name='friend_post'),
    url(r'^delete_friend/(\d+)/$', delete_friend, name = 'delete_friend'),
]

tugas1_profil/urls.py
from django.conf.urls import url
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
    url(r'^$', index, name='index'),
]

tugas1_stats/urls.py
from django.conf.urls import url
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
    url(r'^$', index, name='index'),
]

tugas1_status/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
]

tugas1_friends/models.py
from django.db import models

# Create your models here.

class Friend(models.Model):
	name = models.CharField(max_length=30)
	profile_link = models.URLField()
	added_date = models.DateTimeField(auto_now_add = True)
	

tugas1_profil/models.py
from django.db import models
import datetime

# Create your models here.

class Profil(models.Model):
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other')
    )

    photo = models.URLField(default="https://image.ibb.co/ippEdw/potopropil.png")
    name = models.CharField(max_length=30, default='Tuan Junahedi')
    bday = models.DateField(default=datetime.date(2017,10,5))
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default='Male')
    expertise = models.TextField(max_length=60, default='Exist; Sentient; Real;')
    description = models.TextField(max_length=120, default='A person created by the will of completing TP 1 PPW')
    email = models.EmailField(default='tujuh@yahooo.com')

    def __str__(self):
        return self.name

tugas1_stats/models.py
from django.db import models

# Create your models here.

tugas1_status/models.py
from django.db import models

class Status(models.Model):
    text = models.CharField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)

tugas1_friends/forms.py
from django import forms

class Friends_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan benar',
    }
    name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Masukan nama teman'
    }
    url_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Masukan URL teman, awali dengan http://'
    }
    name = forms.CharField(label='Name', required=True, max_length=30, widget=forms.TextInput(attrs=name_attrs))
    friendURL = forms.URLField(label='URL', required=True, widget=forms.URLInput(attrs=url_attrs))

tugas1_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Status tidak boleh kosong.',
        'invalid': 'Status terlalu panjang.'
    }
    text_attrs = {
        'type': 'text',
        'cols': 40,
        'rows': 3,
        'class': 'status-text',
        'placeholder':'What\'s your story?'
    }

    text = forms.CharField(label='', required=True, max_length=100, widget=forms.TextInput(attrs=text_attrs), error_messages=error_messages)

tugas1_friends/views.py
from django.shortcuts import render
from .forms import Friends_Form
from .models import Friend
import urllib.request
import urllib.error
from django.http import HttpResponseRedirect
# Create your views here.

response = {}
def index(request, success = True):
    friend = Friend.objects.all()
    response['title'] = 'Friends'
    response['form'] = Friends_Form
    response['list'] = friend
    response['success'] = success
    return render(request, 'friends.html', response)

def friend_post(request):
    form = Friends_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        friend = Friend(name=request.POST['name'], profile_link=request.POST['friendURL'])
        if (is_valid_link(request.POST['friendURL'])):
            success = True
            friend.save()
    else:
        success = False
    return index(request, success)

def is_valid_link(link):
    try:
        link_test = urllib.request.urlopen(url=link)
        return True
    except:
        return False

def delete_friend(request, id = None):
    friend = Friend.objects.get(id = id)
    friend.delete()
    return HttpResponseRedirect('/friends')

tugas1_profil/views.py
from django.shortcuts import render
from .models import Profil
from django.http import HttpResponseRedirect


# Create your views here.
user = Profil.objects.get_or_create(pk=1)
user_name = str(user[0])
response = {}
def index(request):
    response['user'] = user[0]
    return render(request, 'profile.html', response)

tugas1_stats/views.py
from django.shortcuts import render
from tugas1_profil.views import user_name
from tugas1_friends.models import Friend
from tugas1_status.models import Status

#TODO Implement
name = user_name

def index(request):
    response = {'title':'Statistics','name':name,'friends':hitungFriends(),'feed':hitungFeeds(),'status':Status.objects.last()}
    return render(request, 'stats.html',response)

def hitungFriends():
    return len(Friend.objects.all())

def hitungFeeds():
    return len(Status.objects.all())

tugas1_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
from tugas1_profil.views import user_name

# Create your views here.
response = {}
def index(request):
    response['author'] = user_name
    status = Status.objects.all()
    response['status'] = status
    response['status_form'] = Status_Form
    html = 'status/status.html'
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['text'] = request.POST['text']
        status = Status(text=response['text'])
        status.save()
    return HttpResponseRedirect('/')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
    hr {
      display: block;
      height: 1px;
      border: 0;
      border-top: 3px solid black;
      margin: 1em 0;
      padding: 0;
    }
    .nav-link {
      font-size: 15px; 
      color: #d5d8e0;
    }
    </style>
</head>
<body style="background-image: url('https://images.designtrends.com/wp-content/uploads/2016/03/29121020/Solid-White-Background.jpg')">
  <header>
      {% include "header.html" %}
  </header>
  <content >
    <div class="container" style="margin-top: 50px; padding-left: 50px; padding-right: 50px">
      {% block content %}
              <!-- content goes here -->
      {% endblock %}
    </div>
  </content>
  <footer>
    <div style="margin-left: 50px;margin-top:50px">
      <!-- TODO Block Footer dan include footer.html -->
      {% block footer %}
      {% include  "footer.html" %}
      {% endblock %}
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<p">&copy;Created by Team 7</p>

templates/header.html
<div class="container-fullwidth">
    <nav class="navbar navbar-expand-lg navbar-inverse bg-inverse" style="background-color:black; margin-bottom: 19px;">
      <a class="navbar-brand" href="#" style="margin-left: 50px; color: #12a812; font-weight: bold">Ling In</a>
      <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="background-color: #d5d5d5">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/"><i class="material-icons" style = "font-size:15px ; color: #d5d8e0">home</i> Home </a>
          </li>
          <li class="nav-item" >
            <a class="nav-link" href="/profile/"><i class="material-icons" style = "font-size: 15px; color: #d5d8e0">perm_identity</i> Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/friends/"><i class="material-icons" style = "font-size: 15px; color: #d5d8e0">perm_contact_calendar</i> Friends</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/stats"><i class="material-icons" style = "font-size: 15px; color: #d5d8e0">list</i> Stat</a>
          </li>
        </ul>
      </div>
    </nav>
</div>

tugas1_friends/templates/friends.html
{% extends "base.html" %}
{% block title %}Friends{% endblock %}
{% block content %}

<style>
	.friend-list{
	  text-align: center;
	  background: #fff;
	  position: relative;
	  z-index: 15;
	  margin-bottom: 60px;
	  -webkit-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
	  -moz-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
	  -o-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
	  box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
	  transition: 0.5s all;
	  -webkit-transition: 0.5s all;
	  -moz-transition: 0.5s all;
	  -o-transition: 0.5s all;
	}

	.friend-list:hover {
	    -webkit-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
	    -moz-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
	    -o-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
	    box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
	    -webkit-transform: translate(0, -5px);
	    -moz-transform: translate(0, -5px);
	    -o-transform: translate(0, -5px);
	    transform: translate(0, -5px);
	}
	.friend-list:after{
	    content:"";
	    display:block;
	    height:25px; /* Which is the padding of div.container */
	    background: #fff;
	}
	.flex{
	  display: flex;
	  flex-direction: row;
	  flex-wrap: wrap;
	  justify-content: flex-start;
	  align-items: flex-start;
	  align-content: flex-start;
	  margin-right: -15px;
	  margin-left: -15px;
	}
	.flex-item{
	  padding: 0 15px;
	  flex-grow: 0;
	  flex-shrink: 0;
	  flex-basis: 33%;
	}

	.friend-list .friend-list-title {
	  font-size: 15px;
	  font-weight: 700;
	  padding: 10px 10px 0;
	}
	.friend-list .friend-list-date-added {
	  font-size: 12px;
	  padding: 0 10px;
	}

	.friend-list .friend-list-image{
	  width:80px;
	  height:100px;
	  padding-top: 10px;
	  padding-bottom: 10px;
	}
	.friend-list .friend-list-description {
	  padding: 10px 25px;
	  z-index: 15;
	  background: #fff;
	  height:50px;
	  text-align: center;
	  overflow: auto;
	}
	.friend-list .friend-list-delete {
	  background: #e45;
	  color: #fff;
	  padding: 10px;
	  font-size: 16px;
	  width: 100%;
	  height: 50px;
	  bottom: 1px;
	  position: absolute;
	  cursor: pointer;
	  z-index: -1;
	  -webkit-border-radius: 0 0px 2px 2px;
	  -moz-border-radius: 0 0px 2px 2px;
	  -o-border-radius: 0 0px 2px 2px;
	  border-radius: 0 0px 2px 2px;
	  -webkit-transition: all 0.3s ease;
	  -moz-transition: all 0.3s ease;
	  -o-transition: all 0.3s ease;
	  transition: all 0.3s ease;
	}
	.friend-list .friend-list-delete {
	  bottom: -50px;
	}
	.friend-list .friend-list-delete:hover{
	  -webkit-animation: neon 1.5s ease-in-out infinite alternate;
	}
	/* styling responsive max-width menandakan bahwa rule css ini hanya akan bekerja untuk layar dengan maksimal 768px, jika lebih dari 768px maka rule ini diabaikan */
	@media only screen and (max-width: 768px) {
	  #input-list form {
	      width: 290px;
	  }
	  .friend-list .friend-list-delete {
	    bottom: -50px;
	  }

	  .flex-item {
	    padding: 0 15px;
	    flex-grow: 0;
	    flex-shrink: 0;
	    flex-basis: 100%;
	  }
	}
</style>
<div>
  <h1>Friends</h1>
  <hr>
<section name="form">
    <h2>Add Friend</h2>
    <form id="form" method="POST" action="{% url 'friends:friend_post'%}">
        {% csrf_token %}
        {{ form }}
        <br>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    {% if success %}
    <p></p>
    {% else %}
    <p>Friend URL is not valid!</p>
    {% endif %}
</section>
<section name="my-list" id="my-list">
	<h2 style="padding-bottom: 15px; padding-top: 15px">Friend List</h2>
        <div class="flex">
            {% if list %}
                {% for data in list %}
                    <div class="flex-item">
                        <div class="friend-list">
                            <div class="friend-list-title">
                                {{data.name}}
                            </div>
                            <div class="friend-list-date-added">
                                Added on {{data.added_date}}
                            </div>
                            <div><img class="friend-list-image" src="https://image.ibb.co/ippEdw/potopropil.png" alt="Profile picture"></div>
                            <div class="friend-list-description">
                                <a href="{{data.profile_link}}">{{data.profile_link}}</a>
                            </div>
                            <div class="friend-list-delete">
                                <div class="friend-list-delete-button" data-id="{{data.id}}" id="delete_button">Delete</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong>Tidak ada teman.
            </div>
            {% endif %}
        </div>
    </div>
</section>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(".friend-list-delete-button").on("click", function(e) {
        var uid = $(this).data('id');
        location.href="delete_friend/" + uid;
      });
    </script>

{% endblock %}

tugas1_profil/templates/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<style>
	table, th, td {
		border: 0px solid black;
		word-wrap:break-word;
		padding-right: 20px;
	}

    .subject{
		text-align: left;
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
    }
    .value{
		text-align: left;
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
    }
	
</style>
<div>
  <h1> Profile </h1>
  <hr>
  <section name="pp" style="padding-top: 7px;text-align: center;">
    <img class="img-circle" id="pp" src={{ user.photo }}  alt="" border="0" height="150" width="150">
  </section>
  

<section name="list">
	<h3 style="text-align: center;">{{ user.name }}</h3>
	<table align="center" style="text-align: left">
		<tbody>
		  <tr>
            <td>Birthday</td>
            <td>{{ user.bday }}</td>
          </tr>
		  <tr>
            <td>Gender</td>
            <td>{{ user.gender }}</td>
          </tr>
		  <tr>
            <td>Expertise</td>
            <td>{{ user.expertise }}</td>
          </tr>
		  <tr>
            <td>Description</td>
            <td>{{ user.description }}</td>
          </tr>
		  <tr>
            <td>Email</td>
            <td>{{ user.email }}</td>
          </tr>		
		</tbody>
	</table>
</section>



 </div>

<br><br>
{% endblock %}

tugas1_stats/templates/stats.html
{% extends "base.html" %}
{% block title %}Statistics{% endblock %}
{% block content %}
<h1> Statistics </h1>
<div class="container" style="text-align:center">

  <hr>
  <h2> <div style="padding-top: 7px;">
    <img class="img-circle" id="pp" src="https://image.ibb.co/ippEdw/potopropil.png"alt="" border="0" height="150" width="150">
  </div> {{ name }} </h2>
  <h4> Friends </h4> {{friends}}
  <h4> Feeds </h4> {{feed}}
  <h4> Latest Post </h4> {{latest_post}}
  {% if status %}
  <div class="container" style="background-color:white;width:60%;color:black;margin-top:1%;text-align:left;padding-bottom:2%;word-wrap: break-word;">
    <h5> <div style="padding-top: 7px;">
      <img class="img-circle" id="pp" src="https://image.ibb.co/ippEdw/potopropil.png"alt="" border="0" height="40" width="40">
  </div> {{ name }} </h5>
    {{ status.text }} <br>
    {{ status.created_date }}
  </div>
  {% else %}
  <h5> No Status </h5>
  {% endif %}

</div>
{% endblock %}

tugas1_status/templates/status/status.html
{% extends "base.html" %}

{% block content %}
<style>
    #input-list {
        margin-bottom: 30px;
    }
    .page-head {
        margin-top: 10px;
        margin-bottom: 10px;
    }
    .list-head {
        margin-bottom: 20px;
    }
    .status-text {
        margin: : 50px;
        display: block;
        width: 100%;
        height: 50px;
        margin-top: 10px;
        margin-bottom: 5px;
    }
    #submit {
        width: 90px;
    }
    .flex-item {
        word-wrap: break-word;
        margin-top: 10px;
        margin-bottom: 10px;
    }
    .author-profile {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: flex-start;
        align-items: flex-start;
        align-content: flex-start;
        background-color: green;
        border-radius: 3px;
        padding: 10px;
    }
    .author-profile-data {
        margin-right: 5px;
        flex-grow: 0;
        flex-shrink: 0;
    }
    .status-list-text {
        background-color: white;
        z-index: 15;
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 5px;
        height: 70px;
        text-align: justify;
    }
    .status-list-date-added {
        background-color: white;
        padding: 6px;
        padding-left: 10px;
        color: gray;
    }
</style>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'status:add_status' %}">
            <h2 class="page-head">Update Status</h2>
            {% csrf_token %}
            {{ status_form }}
            <input id="submit" type="submit" class="btn btn-success" value="Post">
            <br>
        </form>
    </div>
</section>
<section name="my-status" id="my-status">
    <div class="container">
        <h2 class="list-head">My Status</h1>
        <div class="flex">
            {% if status %}
                {% for data in status reversed %}
                    <div class="flex-item">
                        <div class="status-list">
                            <div class="author-profile"> 
                                <div class="author-profile-data" id="author-photo">
                                    <img src="https://image.ibb.co/ippEdw/potopropil.png" alt="" border="0" height="30" width="30" style="border-radius: 50%"/>
                                </div>
                                <div class="author-profile-data" id="author-name" style="color: #e5e5e5">
                                    {{ author }}
                                </div>
                            </div>
                            <div class="status-list-text">
                                {{data.text}}
                            </div>
                            <div class="status-list-date-added">
                                {{data.created_date}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}